# Step 2: turn the events into a thinned SFX cue list and write noon3_sfx_cues.jsx.
# Usage: python3 classify.py events.json ../noon3_sfx_cues.jsx
import json, re, sys
ev = json.load(open(sys.argv[1]))
END = 660.5

def big_move(e):
    t, k, clip, name, pn, dv, v0 = e
    if k == 'camera':
        return dv >= 0.05 if '/Cam/' in pn else dv >= 120
    if k == 'morph':
        if re.search(r'/(W|H)/', pn): return dv >= 160
        if re.search(r'/(CX|CY)/', pn): return dv >= 120
    return k == 'cardpop'

DING  = r'Toast check|^Stamp|^Tick$|Badge pop|check'
PAPER = r'^Page \d'
POP   = r'^Note [A-Z]\w+$|^Callout (bold|info)$|^Pack NOON$|Chip|Badge|^Tag|Swatch|^Use \d|^Stage$|Slot|Pill|^Sun$|Rank no|Rule no|Goal who \d$'
TICK  = r'^Pack (high sun|whole bean|origin|notes)$|^Label |^Origin row|^Rule highlight \d|^Row|^Step \d$|Rule row \d$|^Bullet \d$|File row|Rail row|^Item text|^Rank \d$|Segment|^Time \d|Job area|^Tile|Thumb|Social item|Design name|^Column|Goal question|^Rule slot|^Rule card \d$|^Goal card'
CARD  = r'^Journey line|^Pack (base|build)$|^Graph$|^Motion rule$|^Design (Packaging|Social|Product)|^Pack$|^Bag|^Social post|^Product page|^Folder|^Rule \d (pack|social)|^Brief|^List$|^Radar|Process ring|Sunrise video|^Layout grid|Working doc|^Built from|^Designing'

def kind_of(e):
    t, k, clip, name, pn, dv, v0 = e
    if k == 'window':
        if clip in ('29', '31'): return None          # same window carried over the cut, not a new one
        return 'swish' if clip == '01' else 'window'
    if k == 'press': return 'click'
    if k == 'type': return 'type'
    if name in ('End card',): return 'end'
    if k in ('morph', 'camera', 'cardpop'): return 'whoosh' if big_move(e) else None
    if k == 'pop': return 'pop'
    if k == 'move': return 'tick'
    if k != 'appear': return None
    for cat, rx in (('ding', DING), ('paper', PAPER), ('pop', POP), ('tick', TICK), ('swish', CARD)):
        if re.search(rx, name): return cat
    return None

PRI = ['end', 'accent', 'window', 'click', 'ding', 'type', 'whoosh', 'paper', 'swish', 'pop', 'tick']
cands = []
for e in ev:
    c = kind_of(e)
    if c: cands.append((e[0], c, e[2], e[3], e[4]))
# beats driven by layer markers (word reveals), not keyframes
MANUAL = [(11.72, 'accent', '04', 'NOON wordmark'), (646.0, 'swish', '31', 'A process you can'), (647.08, 'pop', '31', 'Follow.'), (647.64, 'pop', '31', 'Explain.'), (648.36, 'pop', '31', 'Build on.')]
for t, c, clip, name in MANUAL: cands.append((t, c, clip, name, 'marker'))
cands.sort()

# cluster: events within 0.15 s become one cue (highest priority wins; a whoosh keeps a pop/tick riding on it out)
cues = []
for t, c, clip, name, pn in cands:
    if cues and t - cues[-1]['t0'] <= 0.15:
        g = cues[-1]
        if PRI.index(c) < PRI.index(g['c']): g.update(c=c, name=name, pn=pn)
        continue
    cues.append(dict(t=t, t0=t, c=c, clip=clip, name=name, pn=pn))

# thinning
GAP = {'window': 1.5, 'whoosh': 1.2, 'swish': 0.6, 'pop': 0.18, 'tick': 0.18, 'paper': 0.3, 'ding': 0.3}
out = []
for q in cues:
    prev = [p for p in out if q['t'] - p['t'] < 0.22]
    if prev and PRI.index(prev[-1]['c']) <= PRI.index(q['c']): continue
    if prev: out.remove(prev[-1])
    same = [p for p in out if p['c'] == q['c'] and q['t'] - p['t'] < GAP.get(q['c'], 0)]
    if same: continue
    out.append(q)
# typing duration
for q in out:
    m = re.search(r'dur=([\d.]+)', q['pn'])
    q['dur'] = float(m.group(1)) if m else None
# back-to-back typed lines (the three bullets in clip 06) share one typing sound
merged = []
for q in out:
    p = merged[-1] if merged else None
    if p and p['c'] == q['c'] == 'type' and q['t'] - (p['t'] + p['dur']) < 0.3:
        p['dur'] = round(q['t'] + q['dur'] - p['t'], 2); continue
    merged.append(q)
out = merged

def mmss(t): return '%02d:%04.1f' % (int(t // 60), t % 60)
lines = ['// NOON3 SFX cues: [time in NOON3_MAIN (s), sound, note, typing length (s) or 0].',
         '// Generated by sfx/tools/classify.py from the build timings. Edit times here or drag the layers in AE.',
         'var NOON3_SFX_CUES = [']
for q in out:
    nm = {'SHAPE': 'card morph', 'WORLD (camera)': 'camera move'}.get(q['name'], q['name'])
    note = ('%s  %s %s' % (mmss(q['t']), q['clip'], nm)).replace('\\', '/').replace('"', "'")
    note = ''.join(ch if ord(ch) < 128 else '\\u%04X' % ord(ch) for ch in note)
    lines.append('    [%.2f, "%s", "%s", %s],' % (q['t'], q['c'], note, ('%.2f' % q['dur']) if q['dur'] else '0'))
lines[-1] = lines[-1].rstrip(',')
lines.append('];')
open(sys.argv[2], 'w').write('\n'.join(lines) + '\n')
from collections import Counter
print(len(out), Counter(q['c'] for q in out))
mins = Counter(int(q['t'] // 60) for q in out); print(sorted(mins.items()))
gaps = [b['t'] - a['t'] for a, b in zip(out, out[1:])]
long = [(round(a['t'],1), round(b['t'] - a['t'],1)) for a, b in zip(out, out[1:]) if b['t'] - a['t'] > 10]
print('gaps >10s:', long)
